const products = [
  {
    _id: '1',
    name: 'iPhone',
    image: '/img/iphone.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 0,
    rating: 2.5,
    numReviews: 4,
  },
  {
    _id: '2',
    name: 'Macbook',
    image: '/img/airpod.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 3,
    rating: 3.5,
    numReviews: 4,
  },
  {
    _id: '3',

    name: 'iMac',
    image: '/img/iphone.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 3,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: '4',

    name: 'iWatch',
    image: '/img/iphone.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 7,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: '5',

    name: 'Airpods',
    image: '/img/iphone.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 6,
    rating: 5,
    numReviews: 4,
  },
  {
    _id: '6',

    name: 'iPad',
    image: '/img/iphone.jpg',
    description: 'Apples most latest product',
    brand: 'apple',
    category: 'Electronics',
    price: 889.99,
    countInStock: 4,
    rating: 5,
    numReviews: 4,
  },
];

export default products;
